# Challenge 2

In this lab you will partner with another student to conduct **[pair programming](https://en.wikipedia.org/wiki/Pair_programming)**. In the next 60 minutes there will be 2 coding sessions of 30 minutes each. In each sessoin, one student will be the **driver** to write the code to solve the problem while the other student will be the **observer** to watch and review. There will be several iterations of your code because the observer will help the driver review the codes and make improvements until the 15 minute session ends. After the coding session ends, the driver and observer will switch roles.

#### Import all the libraries that are necessary

In [1]:
# import libraries here
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Preparation

#### Import the `Fitbit2.csv` file and name your dataset `fitbit`

In [5]:
fitbit=pd.read_csv('Fitbit2.csv')
fitbit

,Date,Calorie burned,Steps,Distance,Floors,Minutes Sedentary,Minutes Lightly Active,Minutes Fairly Active,Minutes Very Active,Activity Calories,...,Distance_miles,Days,Days_encoded,Work_or_Weekend,Hours Sleep,Sleep efficiency,Yesterday_sleep,Yesterday_sleep_efficiency,Months,Months_encoded
0,2015-05-08,1934,905,0.65,0,1.355,46,0,0,1680,...,0.403891,Friday,4.0,1,6.400000,92.086331,0.000000,0.000000,May,5
1,2015-05-09,3631,18925,14.11,4,611.000,316,61,60,2248,...,8.767545,Saturday,5.0,0,7.566667,92.464358,6.400000,92.086331,May,5
2,2015-05-10,3204,14228,10.57,1,602.000,226,14,77,1719,...,6.567891,Sunday,6.0,0,6.450000,88.761468,7.566667,92.464358,May,5
3,2015-05-11,2673,6756,5.02,8,749.000,190,23,4,9620,...,3.119282,Monday,0.0,1,5.183333,88.857143,6.450000,88.761468,May,5
4,2015-05-12,2495,502,3.73,1,876.000,171,0,0,7360,...,2.317714,Tuesday,1.0,1,6.783333,82.892057,5.183333,88.857143,May,5
5,2015-05-13,276,779,5.79,15,726.000,172,34,18,1094,...,3.597738,Wednesday,2.0,1,6.750000,88.621444,6.783333,82.892057,May,5
6,2015-05-14,2687,5614,4.17,2,782.000,216,13,1,9830,...,2.591117,Thursday,3.0,1,6.350000,91.807229,6.750000,88.621444,May,5
7,2015-05-15,2793,8169,6.07,14,801.000,218,8,7,1092,...,3.771722,Friday,4.0,1,4.483333,87.908497,6.350000,91.807229,May,5
8,2015-05-16,4061,19971,14.84,18,532.000,247,101,118,27,...,9.221146,Saturday,5.0,0,7.533333,89.151874,4.483333,87.908497,May,5
9,2015-05-17,3349,852,6.33,12,606.000,186,46,73,1766,...,3.933278,Sunday,6.0,0,4.483333,92.439863,7.533333,89.151874,May,5
10,2015-05-18,2961,11998,8.91,20,936.000,189,18,51,1371,...,5.536416,Monday,0.0,1,2.783333,92.777778,4.483333,92.439863,May,5
11,2015-05-19,2911,12425,9.23,14,827.000,186,18,54,1351,...,5.735254,Tuesday,1.0,1,6.133333,87.619048,2.783333,92.777778,May,5
12,2015-05-20,2569,6008,4.46,8,783.000,214,15,2,9390,...,2.771315,Wednesday,2.0,1,6.433333,91.904762,6.133333,87.619048,May,5
13,2015-05-21,3228,16291,12.10,18,616.000,237,48,52,1766,...,7.518589,Thursday,3.0,1,5.850000,87.969925,6.433333,91.904762,May,5
14,2015-05-22,2529,6111,4.54,8,820.000,190,14,5,8820,...,2.821024,Friday,4.0,1,5.233333,88.951841,5.850000,87.969925,May,5
15,2015-05-23,4197,17928,13.32,17,533.000,262,79,132,288,...,8.276662,Saturday,5.0,0,7.200000,92.110874,5.233333,88.951841,May,5
16,2015-05-24,3899,13893,10.32,6,641.000,222,33,140,2502,...,6.412549,Sunday,6.0,0,3.733333,82.962963,7.200000,92.110874,May,5
17,2015-05-25,2519,5109,3.80,8,861.000,200,0,0,8470,...,2.361210,Monday,0.0,1,0.000000,0.000000,3.733333,82.962963,May,5
18,2015-05-26,2357,443,3.29,6,1.269,156,0,0,6440,...,2.044311,Tuesday,1.0,1,6.483333,90.465116,0.000000,0.000000,May,5
19,2015-05-27,3209,7498,5.57,18,692.000,196,64,50,1676,...,3.461036,Wednesday,2.0,1,6.350000,92.475728,6.483333,90.465116,May,5
20,2015-05-28,2811,849,6.31,14,771.000,212,8,13,1148,...,3.920851,Thursday,3.0,1,6.950000,85.802469,6.350000,92.475728,May,5
21,2015-05-29,2558,565,4.20,8,789.000,208,0,0,8900,...,2.609758,Friday,4.0,1,7.733333,92.246521,6.950000,85.802469,May,5
22,2015-05-30,417,21479,15.98,16,503.000,230,55,153,2794,...,9.929509,Saturday,5.0,0,5.466667,85.863874,7.733333,92.246521,May,5
23,2015-05-31,3533,18995,14.11,12,660.000,269,86,43,2092,...,8.767545,Sunday,6.0,0,7.100000,86.060606,5.466667,85.863874,May,5
24,2015-06-01,3354,16836,12.51,8,586.000,248,35,70,1862,...,7.773351,Monday,0.0,1,7.166667,88.842975,7.100000,86.060606,June,6
25,2015-06-02,3369,15944,11.85,29,640.000,214,15,93,1827,...,7.363246,Tuesday,1.0,1,6.266667,86.238532,7.166667,88.842975,June,6
26,2015-06-03,3168,14273,10.60,11,721.000,178,16,89,1592,...,6.586533,Wednesday,2.0,1,5.200000,84.552846,6.266667,86.238532,June,6
27,2015-06-04,347,1606,11.93,11,724.000,239,38,70,1939,...,7.412956,Thursday,3.0,1,6.466667,93.493976,5.200000,84.552846,June,6
28,2015-06-05,3134,13594,10.10,16,677.000,215,36,52,1583,...,6.275847,Friday,4.0,1,6.816667,87.393162,6.466667,93.493976,June,6
29,2015-06-06,3436,1548,11.50,11,520.000,246,78,42,1927,...,7.145766,Saturday,5.0,0,7.100000,86.060606,6.816667,87.393162,June,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,2016-04-08,3241,13441,10.04,2,449.000,439,0,0,1874,...,6.238565,Friday,4.0,1,6.316667,89.176471,5.983333,96.246649,April,4
338,2016-04-09,3038,10216,7.59,0,535.000,390,0,0,1607,...,4.716206,Saturday,5.0,0,8.450000,96.571429,6.316667,89.176471,April,4
339,2016-04-10,2304,5634,4.19,0,921.000,92,41,4,6590,...,2.603544,Sunday,6.0,0,5.100000,89.736070,8.450000,96.571429,April,4
340,2016-04-11,3419,17422,13.38,34,674.000,290,14,61,1928,...,8.313944,Monday,0.0,1,6.783333,89.059081,5.100000,89.736070,April,4
341,2016-04-12,3179,14475,10.92,14,664.000,291,10,47,1696,...,6.785371,Tuesday,1.0,1,5.900000,90.537084,6.783333,89.059081,April,4
342,2016-04-13,3427,17777,13.66,20,696.000,276,10,80,1967,...,8.487928,Wednesday,2.0,1,6.083333,84.883721,5.900000,90.537084,April,4
343,2016-04-14,3479,19087,14.65,17,711.000,221,12,96,1954,...,9.103085,Thursday,3.0,1,4.633333,91.447368,6.083333,84.883721,April,4
344,2016-04-15,3501,1629,12.20,12,467.000,427,25,11,2166,...,7.580726,Friday,4.0,1,6.600000,88.789238,4.633333,91.447368,April,4
345,2016-04-16,3342,14252,10.64,6,675.000,323,60,18,1947,...,6.611387,Saturday,5.0,0,6.733333,85.774947,6.600000,88.789238,April,4
346,2016-04-17,2769,8262,6.14,3,1.089,302,0,0,1266,...,3.815218,Sunday,6.0,0,0.000000,0.000000,6.733333,85.774947,April,4
347,2016-04-18,3486,1945,15.06,18,860.000,190,6,98,1926,...,9.357847,Monday,0.0,1,5.116667,91.641791,0.000000,0.000000,April,4
348,2016-04-19,3596,17232,13.61,17,1.002,262,4,88,2085,...,8.456859,Tuesday,1.0,1,0.000000,0.000000,5.116667,91.641791,April,4
349,2016-04-20,3321,16946,12.93,25,762.000,238,5,67,1795,...,8.034327,Wednesday,2.0,1,6.850000,92.986425,0.000000,0.000000,April,4
350,2016-04-21,3464,19183,14.67,24,723.000,218,7,97,1964,...,9.115513,Thursday,3.0,1,5.683333,92.663043,6.850000,92.986425,April,4
351,2016-04-22,3328,12963,9.66,10,404.000,436,14,10,202,...,6.002444,Friday,4.0,1,7.166667,87.398374,5.683333,92.663043,April,4
352,2016-04-23,2612,6456,4.80,6,782.000,305,0,0,1135,...,2.982581,Saturday,5.0,0,5.083333,87.643678,7.166667,87.398374,April,4
353,2016-04-24,2863,10413,7.73,6,700.000,269,28,24,1411,...,4.803198,Sunday,6.0,0,6.250000,87.006961,5.083333,87.643678,April,4
354,2016-04-25,3175,10499,7.80,0,661.000,430,9,4,1805,...,4.846694,Monday,0.0,1,3.950000,89.433962,6.250000,87.006961,April,4
355,2016-04-26,3357,17226,12.97,19,751.000,185,16,95,1798,...,8.059182,Tuesday,1.0,1,6.000000,94.736842,3.950000,89.433962,April,4
356,2016-04-27,3631,19784,15.51,25,694.000,151,26,128,207,...,9.637464,Wednesday,2.0,1,6.016667,88.048780,6.000000,94.736842,April,4
357,2016-04-28,403,25571,19.30,15,606.000,293,42,129,2711,...,11.992460,Thursday,3.0,1,6.233333,86.976744,6.016667,88.048780,April,4
358,2016-04-29,3442,17528,13.36,15,594.000,239,8,82,1931,...,8.301517,Friday,4.0,1,5.800000,94.565217,6.233333,86.976744,April,4
359,2016-04-30,3061,9831,7.30,1,561.000,414,0,0,1651,...,4.536008,Saturday,5.0,0,7.566667,90.438247,5.800000,94.565217,April,4
360,2016-05-01,3331,14262,10.60,5,666.000,361,21,41,1937,...,6.586533,Sunday,6.0,0,5.783333,89.432990,7.566667,90.438247,May,5
361,2016-05-02,2989,13236,9.98,12,770.000,234,8,38,1477,...,6.201283,Monday,0.0,1,5.233333,90.229885,5.783333,89.432990,May,5
362,2016-05-03,3796,18588,14.13,16,599.000,275,49,79,236,...,8.779972,Tuesday,1.0,1,6.283333,91.951220,5.233333,90.229885,May,5
363,2016-05-04,3525,16382,12.39,16,684.000,333,10,55,2075,...,7.698787,Wednesday,2.0,1,6.766667,95.081967,6.283333,91.951220,May,5
364,2016-05-05,3649,21913,16.40,19,701.000,287,29,90,2249,...,10.190484,Thursday,3.0,1,4.666667,88.888889,6.766667,95.081967,May,5
365,2016-05-06,3539,19023,14.79,15,575.000,298,8,85,2112,...,9.190077,Friday,4.0,1,6.166667,89.805825,4.666667,88.888889,May,5
366,2016-05-07,304,9526,7.08,2,564.000,370,13,10,1604,...,4.399307,Saturday,5.0,0,8.366667,89.165187,6.166667,89.805825,May,5

## Coding Session I - 30 minutes

From the Fitbit data, we want to visually understand: 

1. **How the average number of steps change by month. Use the appropriate visualization to show the median steps by month?**
1. **Is Fitbitter more active on weekend or workdays?**

##### All plots must be in the same jupyter notebook cell.

Hints:

- Use `Months_encoded` and `Week_or Weekend` columns
- Use `matplolib.pyplot` object oriented API
- Set your size figure to `12,4`
- Explore `plt.sca`
- Explore `plt.xticks`
- Save your figures

In [12]:
# Driver 1 enter codes here
df_st = pd.DataFrame(fitbit)

df_st_median = df_st.groupby(["Months_encoded"]).agg({"Steps":"median"})

#plt.figure(figsize=(12, 4))
#plt.plot(df_st_median["Months_encoded"],df_st_median["Steps"],'m')

'''
plt.figure(figsize=(12, 4))
plt.subplot('211')
plt.plot(x,y,'m')
plt.title('Función lineal')
plt.ylabel(r'$y=2x$')
plt.subplot('212')
plt.plot(x,z,'g')
plt.title('Función cuadrática')
plt.ylabel(r'$z=x^2$')
plt.xlabel('Valores de x')
'''

display(df_st_median)

                  Steps
Months_encoded
1               10366.0
2                9235.0
3               11122.0
4               13846.5
5               11998.0
6               12935.5
7               10644.0
8               12213.0
9                9343.0
10               7865.0
11               9453.5
12               8531.0

## Coding Session II - 30 minutes

**Write a loop to plot 3 scatter plots of the following features:**

1. **`Minutes Lightly Active`  vs `Steps`**
1. **`Minutes Very Active` vs `Steps`**
1. **`Minutes Sedentary` vs `Steps`**

In [ ]:
# Driver 2 enter codes here